# Generated by Django 4.1.1 on 2022-09-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='translatepage',
            name='bio',
            field=models.CharField(default='bio mavjud emas', max_length=200),
        ),
    ]
